runtime: go111

default_expiration: "3650d"

handlers:
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301
- url: /article/res
  static_dir: articles/res
  secure: always
  redirect_http_response_code: 301
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
